using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EnergyMonitoring.Migrations
{
    /// <inheritdoc />
    public partial class ManualPendingFix : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder) { migrationBuilder.AddColumn<DateTime>(name: "CreatedAt", table: "SolarPlants", type: "datetime2", nullable: false, defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)); migrationBuilder.AddColumn<bool>(name: "IsActive", table: "SolarPlants", type: "bit", nullable: false, defaultValue: false); migrationBuilder.AlterColumn<DateTime>(name: "Timestamp", table: "EnergyReadings", type: "datetime2", nullable: false, comment: "Fecha de la lectura", oldClrType: typeof(DateTime), oldType: "datetime2", oldComment: "Fecha"); migrationBuilder.AlterColumn<decimal>(name: "ImportKWh", table: "EnergyReadings", type: "decimal(18,3)", nullable: false, comment: "Energía importada", oldClrType: typeof(decimal), oldType: "decimal(18,2)", oldComment: "Energía importada"); migrationBuilder.AlterColumn<decimal>(name: "GeneratedKWh", table: "EnergyReadings", type: "decimal(18,3)", nullable: false, comment: "Energía generada", oldClrType: typeof(decimal), oldType: "decimal(18,2)", oldComment: "Energía generada"); migrationBuilder.AlterColumn<decimal>(name: "ExportKWh", table: "EnergyReadings", type: "decimal(18,3)", nullable: false, comment: "Energía exportada", oldClrType: typeof(decimal), oldType: "decimal(18,2)", oldComment: "Energía exportada"); migrationBuilder.AlterColumn<decimal>(name: "ConsumedKWh", table: "EnergyReadings", type: "decimal(18,3)", nullable: false, comment: "Energía consumida", oldClrType: typeof(decimal), oldType: "decimal(18,2)", oldComment: "Energía consumida"); migrationBuilder.AddColumn<bool>(name: "IsActive", table: "Devices", type: "bit", nullable: false, defaultValue: false); migrationBuilder.AddColumn<string>(name: "CreatedByUserId", table: "DeviceMeasurements", type: "nvarchar(max)", nullable: false, defaultValue: ""); migrationBuilder.CreateIndex(name: "IX_EnergyReadings_Timestamp", table: "EnergyReadings", column: "Timestamp"); }
        protected override void Down(MigrationBuilder migrationBuilder) { migrationBuilder.DropIndex( name: "IX_EnergyReadings_Timestamp", table: "EnergyReadings"); migrationBuilder.DropColumn( name: "CreatedAt", table: "SolarPlants"); migrationBuilder.DropColumn( name: "IsActive", table: "SolarPlants"); migrationBuilder.DropColumn( name: "IsActive", table: "Devices"); migrationBuilder.DropColumn( name: "CreatedByUserId", table: "DeviceMeasurements"); migrationBuilder.AlterColumn<DateTime>( name: "Timestamp", table: "EnergyReadings", type: "datetime2", nullable: false, comment: "Fecha", oldClrType: typeof(DateTime), oldType: "datetime2", oldComment: "Fecha de la lectura"); migrationBuilder.AlterColumn<decimal>( name: "ImportKWh", table: "EnergyReadings", type: "decimal(18,2)", nullable: false, comment: "Energía importada", oldClrType: typeof(decimal), oldType: "decimal(18,3)", oldComment: "Energía importada"); migrationBuilder.AlterColumn<decimal>( name: "GeneratedKWh", table: "EnergyReadings", type: "decimal(18,2)", nullable: false, comment: "Energía generada", oldClrType: typeof(decimal), oldType: "decimal(18,3)", oldComment: "Energía generada"); migrationBuilder.AlterColumn<decimal>( name: "ExportKWh", table: "EnergyReadings", type: "decimal(18,2)", nullable: false, comment: "Energía exportada", oldClrType: typeof(decimal), oldType: "decimal(18,3)", oldComment: "Energía exportada"); migrationBuilder.AlterColumn<decimal>( name: "ConsumedKWh", table: "EnergyReadings", type: "decimal(18,2)", nullable: false, comment: "Energía consumida", oldClrType: typeof(decimal), oldType: "decimal(18,3)", oldComment: "Energía consumida"); }

    }
}