namespace EnergyMonitoring.Domain.Entities
{
    /// <summary>
    /// Represents energy measurements for a time period.
    /// Representa las mediciones de energía en un periodo.
    /// </summary>
    public class EnergyReading
    {
        /// <summary>
        /// Unique identifier.
        /// Identificador único.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Solar plant reference.
        /// Planta solar relacionada.
        /// </summary>
        public Guid SolarPlantId { get; set; }

        /// <summary>
        /// Energy generated by solar panels (kWh).
        /// Energía generada por los paneles.
        /// </summary>
        public decimal GeneratedKWh { get; set; }

        /// <summary>
        /// Energy consumed locally (kWh).
        /// Energía consumida.
        /// </summary>
        public decimal ConsumedKWh { get; set; }

        /// <summary>
        /// Energy exported to the grid.
        /// Energía enviada a la red.
        /// </summary>
        public decimal ExportKWh { get; set; }

        /// <summary>
        /// Energy imported from the grid.
        /// Energía tomada de la red.
        /// </summary>
        public decimal ImportKWh { get; set; }

        /// <summary>
        /// Date and time of the reading.
        /// Fecha y hora de la lectura.
        /// </summary>
        public DateTime Timestamp { get; set; }

        public string RecordedByUserId { get; set; } = default!;
        public ApplicationUser RecordedByUser { get; set; } = default!;
        public SolarPlant SolarPlant { get; set; } = default!;
    }
}
